apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: kubernetes.io/basic-auth
#real world this would never exist as plain text in the repo
stringData:
  password: secure
#obviously would use hashicorp vault or 
#some more secure method of providing secrets in a real world deployment, but we read this secret
#into the mysql deployment via an env var, just wanted to demostrate configurability  